lista_autos = [
    {"marca": "Toyota", "año": 2018, "modelo": "Corolla", "min_km": 50000, "max_km": 100000, "min_precio": 25000, "transmicion": "automática", "uso": "urbano", "consumo": "medio", "tamaño": "Sedán"},
    {"marca": "Honda", "año": 2020, "modelo": "Civic", "min_km": 20000, "max_km": 60000, "min_precio": 30000, "transmicion": "manual", "uso": "familiar", "consumo": "bajo", "tamaño": "Sedán"},
    {"marca": "Ford", "año": 2015, "modelo": "Escape", "min_km": 80000, "max_km": 120000, "min_precio": 28000, "transmicion": "automática", "uso": "todo terreno", "consumo": "alto", "tamaño": "SUV"},
    {"marca": "Chevrolet", "año": 2017, "modelo": "Malibu", "min_km": 60000, "max_km": 110000, "min_precio": 24000, "transmicion": "manual", "uso": "urbano", "consumo": "medio", "tamaño": "Sedán"},
    {"marca": "Nissan", "año": 2019, "modelo": "Altima", "min_km": 30000, "max_km": 70000, "min_precio": 26000, "transmicion": "automática", "uso": "familiar", "consumo": "bajo", "tamaño": "Sedán"},
    {"marca": "Jeep", "año": 2014, "modelo": "Wrangler", "min_km": 90000, "max_km": 150000, "min_precio": 35000, "transmicion": "manual", "uso": "todo terreno", "consumo": "alto", "tamaño": "SUV"},
    {"marca": "BMW", "año": 2021, "modelo": "X5", "min_km": 15000, "max_km": 40000, "min_precio": 55000, "transmicion": "automática", "uso": "viajes de larga distancia", "consumo": "alto", "tamaño": "SUV"},
    {"marca": "Audi", "año": 2020, "modelo": "A4", "min_km": 25000, "max_km": 50000, "min_precio": 45000, "transmicion": "automática", "uso": "urbano", "consumo": "bajo", "tamaño": "Sedán"},
    {"marca": "Mazda", "año": 2016, "modelo": "CX-5", "min_km": 70000, "max_km": 120000, "min_precio": 22000, "transmicion": "manual", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Hyundai", "año": 2019, "modelo": "Elantra", "min_km": 40000, "max_km": 80000, "min_precio": 21000, "transmicion": "automática", "uso": "urbano", "consumo": "medio", "tamaño": "Sedán"},
    {"marca": "Kia", "año": 2018, "modelo": "Sorento", "min_km": 50000, "max_km": 90000, "min_precio": 25000, "transmicion": "manual", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Tesla", "año": 2022, "modelo": "Model 3", "min_km": 5000, "max_km": 30000, "min_precio": 60000, "transmicion": "automática", "uso": "urbano", "consumo": "muy bajo", "tamaño": "Sedán"},
    {"marca": "Volkswagen", "año": 2017, "modelo": "Golf", "min_km": 60000, "max_km": 110000, "min_precio": 19000, "transmicion": "manual", "uso": "urbano", "consumo": "bajo", "tamaño": "Hatchback"},
    {"marca": "Chevrolet", "año": 2016, "modelo": "Traverse", "min_km": 85000, "max_km": 130000, "min_precio": 27000, "transmicion": "automática", "uso": "viajes de larga distancia", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Ford", "año": 2015, "modelo": "F-150", "min_km": 100000, "max_km": 200000, "min_precio": 40000, "transmicion": "manual", "uso": "cargamento pesado", "consumo": "muy alto", "tamaño": "Pick-up"},
    {"marca": "Ram", "año": 2020, "modelo": "1500", "min_km": 30000, "max_km": 70000, "min_precio": 45000, "transmicion": "automática", "uso": "cargamento pesado", "consumo": "muy alto", "tamaño": "Pick-up"},
    {"marca": "Toyota", "año": 2021, "modelo": "Highlander", "min_km": 15000, "max_km": 50000, "min_precio": 50000, "transmicion": "automática", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Porsche", "año": 2022, "modelo": "911", "min_km": 10000, "max_km": 30000, "min_precio": 120000, "transmicion": "manual", "uso": "deportivo", "consumo": "alto", "tamaño": "Coupé"},
    {"marca": "Subaru", "año": 2018, "modelo": "Outback", "min_km": 60000, "max_km": 110000, "min_precio": 32000, "transmicion": "manual", "uso": "viajes de larga distancia", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Land Rover", "año": 2021, "modelo": "Defender", "min_km": 20000, "max_km": 60000, "min_precio": 70000, "transmicion": "automática", "uso": "todo terreno", "consumo": "muy alto", "tamaño": "SUV"},
    {"marca": "Dodge", "año": 2016, "modelo": "Charger", "min_km": 85000, "max_km": 120000, "min_precio": 27000, "transmicion": "manual", "uso": "deportivo", "consumo": "alto", "tamaño": "Sedán"},
    {"marca": "Mini", "año": 2020, "modelo": "Cooper", "min_km": 20000, "max_km": 50000, "min_precio": 23000, "transmicion": "automática", "uso": "urbano", "consumo": "bajo", "tamaño": "Hatchback"},
    {"marca": "Fiat", "año": 2017, "modelo": "500X", "min_km": 40000, "max_km": 80000, "min_precio": 19000, "transmicion": "manual", "uso": "urbano", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Mazda", "año": 2021, "modelo": "MX-5", "min_km": 10000, "max_km": 40000, "min_precio": 35000, "transmicion": "manual", "uso": "deportivo", "consumo": "alto", "tamaño": "Coupé"},
    {"marca": "GMC", "año": 2019, "modelo": "Sierra 1500", "min_km": 30000, "max_km": 90000, "min_precio": 43000, "transmicion": "automática", "uso": "cargamento pesado", "consumo": "muy alto", "tamaño": "Pick-up"},
    {"marca": "Suzuki", "año": 2018, "modelo": "Jimny", "min_km": 50000, "max_km": 100000, "min_precio": 23000, "transmicion": "manual", "uso": "todo terreno", "consumo": "alto", "tamaño": "SUV"},
    {"marca": "Toyota", "año": 2019, "modelo": "RAV4", "min_km": 30000, "max_km": 70000, "min_precio": 33000, "transmicion": "automática", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Chevrolet", "año": 2017, "modelo": "Colorado", "min_km": 75000, "max_km": 130000, "min_precio": 28000, "transmicion": "manual", "uso": "cargamento pesado", "consumo": "alto", "tamaño": "Pick-up"},
    {"marca": "Mercedes-Benz", "año": 2021, "modelo": "E-Class", "min_km": 20000, "max_km": 50000, "min_precio": 70000, "transmicion": "automática", "uso": "viajes de larga distancia", "consumo": "alto", "tamaño": "Sedán"},
    {"marca": "Lexus", "año": 2020, "modelo": "RX", "min_km": 25000, "max_km": 60000, "min_precio": 55000, "transmicion": "automática", "uso": "familiar", "consumo": "bajo", "tamaño": "SUV"},
    {"marca": "Honda", "año": 2016, "modelo": "CR-V", "min_km": 70000, "max_km": 110000, "min_precio": 27000, "transmicion": "manual", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Nissan", "año": 2022, "modelo": "Z", "min_km": 5000, "max_km": 30000, "min_precio": 45000, "transmicion": "manual", "uso": "deportivo", "consumo": "alto", "tamaño": "Coupé"},
    {"marca": "Ford", "año": 2020, "modelo": "Bronco", "min_km": 15000, "max_km": 50000, "min_precio": 48000, "transmicion": "automática", "uso": "todo terreno", "consumo": "alto", "tamaño": "SUV"},
    {"marca": "Tesla", "año": 2023, "modelo": "Model X", "min_km": 5000, "max_km": 30000, "min_precio": 90000, "transmicion": "automática", "uso": "familiar", "consumo": "muy bajo", "tamaño": "SUV"},
    {"marca": "Hyundai", "año": 2018, "modelo": "Tucson", "min_km": 40000, "max_km": 90000, "min_precio": 25000, "transmicion": "manual", "uso": "familiar", "consumo": "medio", "tamaño": "SUV"},
    {"marca": "Chevrolet", "año": 2022, "modelo": "Camaro", "min_km": 15000, "max_km": 45000, "min_precio": 50000, "transmicion": "manual", "uso": "deportivo", "consumo": "alto", "tamaño": "Coupé"}
]